### ISSUE TITLE
Building project in Xcode 9

### ISSUE THREAD

**Issue by ynewdev** [voximplant/iosVoxImplantDemoNewAPI#1]
Hello.

How can I build this project in Xcode 9? When I build it now I get error: 
```
ld: ./iosVoxImplantDemoNewAPI/Pods/VoxImplantSDK/VoxImplant.framework/VoxImplant compiled with older version of Swift language (3.0) than previous files (4.0) file './iosVoxImplantDemoNewAPI/Pods/VoxImplantSDK/VoxImplant.framework/VoxImplant' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by grigoryvp** [comment]
Please check this stackoverflow question, it's realted to how XCode works: https://stackoverflow.com/questions/38016143/how-to-delete-derived-data-in-xcode-8

**Comment by ynewdev** [comment]
How it can relate with Derived data? I only clone your project, execute pod install, launch Xcode 9 with workspace and build project. 

Problem relate with VoxImplant.framework with already compiled and I only downloaded it.

**Comment by YuliaGrigorieva** [comment]
Hello!

We have updated the project to the latest version of VoxImplant iOS SDK.
Please pull the latest changes, update pods and try again.

**Comment by ynewdev** [comment]
Thanks. It works for me now.
