### ISSUE TITLE
Doesn't call VIVideoPreprocessDelegate method

### ISSUE THREAD

**Issue by Alenkor** [voximplant/iosVoxImplantDemoNewAPI#2]
Hello! There is a problem - when I am trying to use CameraPreprocessor the method of the delegate preprocessVideoFrame is never called. The problem is relevant for both - my project and your demo app. When I uncomment this line - “// uncomment to use camera preprocess callback” - it doesn’t help. The delegate is not nil. Thank you for your reply in advance.

**Comment by nasakinmaxim** [comment]
Same here.

**Comment by Hastewave** [comment]
I've got the same issue!

**Comment by 3Bepo6ou** [comment]
Seems like me've met alike problem.
Dear Voximplant Team, please advice asap!

**Comment by YuliaGrigorieva** [comment]
Hello!

Thank you for the reports!
We have found the regression is introduced in 2.9.0 release, we are working hard to resolve it the nearest time.

While it is not resolved, please use 2.8.0 version.

**Comment by niveuseverto** [comment]
Greetings.

This issue is resolved in 2.11.0 (d5c8264425a6d5e5284705125c5d34c77c7475f8).

Please, update and check if everything is working now.
