### ISSUE TITLE
VICameraManager error

### ISSUE THREAD

**Issue by ekharlamova** [voximplant/iosVoxImplantDemoNewAPI#5]
When the creation of camera preprocessor is uncommented in AppDelegate and the app tries to use it for processing video it throws the exception with an error: '-[VoxImplantDemo.CameraPreprocessor videoPreprocessDelegate]: unrecognized selector sent to instance'

**Comment by niveuseverto** [comment]
Greetings,
Thank you for report.

This is already fixed and will be shipped with next release of SDK.
If you need this feature, you can use v2.11.0 at this moment.

**Comment by niveuseverto** [comment]
Greetings.

This issue is resolved in 2.13.0.

Please, update and check if everything is working now.
